### ISSUE TITLE
谢谢大佬 node很好用 可以请求写下Sunert大佬的腾讯新闻吗

### ISSUE THREAD

**Issue by ioi32666** [jiuli12/Script#2]
地址：https://github.com/Sunert/Scripts/blob/master/Task/txnews.js

**Comment by jiuli12** [comment]
你是那个？让我很惊讶。腾讯新闻一天大概多少？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiuli12/Script"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 下午2:24
收件人:&nbsp;"jiuli12/Script"<Script@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jiuli12/Script] 谢谢大佬 node很好用 可以请求写下Sunert大佬的腾讯新闻吗 (#2)





 
地址：https://github.com/Sunert/Scripts/blob/master/Task/txnews.js

**Comment by ioi32666** [comment]
就无意中看到的，很厉害，毛很少吧 但是我一直挂着 还挺多人玩的

**Comment by jiuli12** [comment]
行 有空我瞅瞅吧。还有什么好的毛 推荐下。刚开始玩这玩意
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiuli12/Script"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 下午2:49
收件人:&nbsp;"jiuli12/Script"<Script@noreply.github.com&gt;;
抄送:&nbsp;"TiAmo"<805543598@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jiuli12/Script] 谢谢大佬 node很好用 可以请求写下Sunert大佬的腾讯新闻吗 (#2)





 
就无意中看到的，很厉害，毛很少吧 但是我一直挂着 还挺多人玩的

**Comment by ioi32666** [comment]
企鹅阅读，中青，腾讯新闻，聚看点，喜马拉雅，我玩的这几个

**Comment by jiuli12** [comment]
我改了 中青 聚看点&nbsp;
喜马拉雅ac就行。我看也就这些了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiuli12/Script"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 下午3:02
收件人:&nbsp;"jiuli12/Script"<Script@noreply.github.com&gt;;
抄送:&nbsp;"TiAmo"<805543598@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jiuli12/Script] 谢谢大佬 node很好用 可以请求写下Sunert大佬的腾讯新闻吗 (#2)





 
企鹅阅读，中青，腾讯新闻，聚看点，喜马拉雅，我玩的这几个

**Comment by ioi32666** [comment]
行吧 谢谢大佬

**Comment by ioi32666** [comment]
好像是需要点一个链接进入活动以后才会有，我记不太清楚了，找了一下没找到
